version: "3"

networks:
  nordkraft-bot-network:
    driver: bridge

volumes:
  nordkraft-bot-db-volume:

services:
  # Client
  nordkraft-bot-client:
    build:
      context: ./front/nordkraft-bot-client
      dockerfile: Dockerfile
    
    ports:
      - "3000:3000"

    depends_on:
      - nordkraft-bot-api
    
    networks:
      - nordkraft-bot-network

  # API
  nordkraft-bot-api:
    build:
      context: ./back
      dockerfile: Dockerfile
    command: sh start_server.sh development
    depends_on:
      - nordkraft-bot-db
    env_file:
      - ./.env
    volumes:
      - ./app.log:/app/app.log
    expose: 
      - ${PORT}
    ports:
      - "${PORT}:${PORT}"
    environment:
      - "PORT=${PORT}"
    networks:
      - nordkraft-bot-network
    depends_on:
      - nordkraft-bot-db

  # Database
  nordkraft-bot-db:
    image: postgres:latest
    expose:
      - ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    
    restart: always
    volumes:
      - nordkraft-bot-db-volume:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

    networks:
      - nordkraft-bot-network
